### ISSUE TITLE
Permanent error on any command

### ISSUE THREAD

**Issue by tenorok** [google/closure-linter#105]
Hello, I'm user of OS X and installed gjslint according to [this instruction](https://developers.google.com/closure/utilities/docs/linter_howto#mac-os-x), the installation was successful.

But when I run any command, even help `gjslint --help`, it's throw an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/gjslint", line 11, in <module>
    load_entry_point('closure-linter==2.3.19', 'console_scripts', 'gjslint')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/closure_linter/gjslint.py", line 46, in <module>
    import gflags as flags
  File "/usr/local/lib/python2.7/site-packages/gflags/__init__.py", line 58, in <module>
    import six
ImportError: No module named six
```

I don't know python, can you suggest me please, what I doing wrong?

Some additional information:
```
› python --version
Python 2.7.10
```

```
› which gjslint
/usr/local/bin/gjslint
```

```
› system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G1108)
      Kernel Version: Darwin 15.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

**Comment by rumpeltux** [comment]
Thanks for your report.
Did you try fixing the problem according to the following? http://stackoverflow.com/questions/13967428/importerror-no-module-named-six
