### ISSUE TITLE
Python version 2.x print in error_fixer.py

### ISSUE THREAD

**Issue by cnobile2012** [google/closure-linter#108]
When I ran `fixjsstyle`, in Python 3.5.2, I got this traceback (closure-linter-2.3.13):
```
Traceback (most recent call last):
  File "/home/cnobile/.virtualenvs/testsite/bin/fixjsstyle", line 7, in <module>
    from closure_linter.fixjsstyle import main
  File "/home/cnobile/.virtualenvs/testsite/lib/python3.5/site-packages/closure_linter/fixjsstyle.py", line 25, in <module>
    from closure_linter import error_fixer
  File "/home/cnobile/.virtualenvs/testsite/lib/python3.5/site-packages/closure_linter/error_fixer.py", line 489
    print 'Fixed %d errors in %s' % (self._file_fix_count, self._file_name)
                                ^
SyntaxError: invalid syntax
```

**Comment by rumpeltux** [comment]
Yes, unfortunately python-3 is not supported by this project and since it’s deprecated there won’t be any work on it either.
