### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/closure-linter#81]
```
What steps will reproduce the problem?
 - Run gjslint.py using Python 3.

What is the expected output?
 - Normal linting over the source files.

What do you see instead?
Traceback (most recent call last):
  File "d:\Programming\repo\node_modules\closure-linter-wrapper\tools\gjslint.py", line 13, in <module>
    from closure_linter import gjslint
  File "d:\Programming\repo\node_modules\closure-linter-wrapper\tools\closure_linter\gjslint.py", line 168
    print '%s: %d' % (path, len(path_errors))
                 ^
SyntaxError: invalid syntax


What version of the product are you using?
 - 2.3.1.2

On what operating system?
 - Windows 7

```

Original issue reported on code.google.com by `rand...@gmail.com` on 17 Jun 2014 at 2:23

**Comment by ngvtuan** [comment]
I have got same error.


C:\Python34\Scripts>gjslint
Traceback (most recent call last):
  File "C:\Python34\Scripts\gjslint-script.py", line 9, in <module>
    load_entry_point('closure-linter==2.3.13', 'console_scripts', 'gjslint')()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python34\lib\site-packages\closure_linter\gjslint.py", line 168
    print '%s: %d' % (path, len(path_errors))
                 ^
SyntaxError: invalid syntax

**Comment by tsauerwein** [comment]
Are there any plans to support Python 3 in the near future?

**Comment by rumpeltux** [comment]
There are no such plans. This project is as good as deprecated and not actively developed anymore. We’ll update with more information on alternatives in the near future.
